### ISSUE TITLE
Read permission errors

### ISSUE THREAD

**Issue by kambysese** [ilogue/niprov#94]
@ilogue not exactly sure why permission errors on read only raw files started popping up?

>Traceback (most recent call last):
  File "/home/ktavabi/Projects/niprov/niprov/adding.py", line 70, in add
    img.inspect()
  File "/home/ktavabi/Projects/niprov/niprov/fif.py", line 13, in inspect
    provenance = super(FifFile, self).inspect()
  File "/home/ktavabi/Projects/niprov/niprov/basefile.py", line 23, in inspect
    self.provenance['hash'] = self.hasher.digest(self.path)
  File "/home/ktavabi/Projects/niprov/niprov/hashing.py", line 19, in digest
    with open(filename, "r+b") as f:
IOError: [Errno 13] Permission denied: '/mnt/ALAYA/data/ilabs/bad_baby/bad_129a/raw_fif/bad_129a_mmn_raw.fif'
[provenance:warning] Error inspecting file: /mnt/ALAYA/data/ilabs/bad_baby/bad_129a/raw_fif/bad_129a_mmn_raw.fif

**Comment by ilogue** [comment]
Can you try with:
On Feb 1, 2016 10:33, "Kambiz" <notifications@github.com> wrote:
>
> @ilogue not exactly sure why permission errors on read only raw files
started popping up?
>>
>> Traceback (most recent call last):
>> File "/home/ktavabi/Projects/niprov/niprov/adding.py", line 70, in add
>> img.inspect()
>> File "/home/ktavabi/Projects/niprov/niprov/fif.py", line 13, in inspect
>> provenance = super(FifFile, self).inspect()
>> File "/home/ktavabi/Projects/niprov/niprov/basefile.py", line 23, in
inspect
>> self.provenance['hash'] = self.hasher.digest(self.path)
>> File "/home/ktavabi/Projects/niprov/niprov/hashing.py", line 19, in
digest
>> with open(filename, "r+b") as f:
"rb" instead of "r+b"

>> IOError: [Errno 13] Permission denied:
'/mnt/ALAYA/data/ilabs/bad_baby/bad_129a/raw_fif/bad_129a_mmn_raw.fif'
>> [provenance:warning] Error inspecting file:
/mnt/ALAYA/data/ilabs/bad_baby/bad_129a/raw_fif/bad_129a_mmn_raw.fif

**Comment by ilogue** [comment]
If that work, please PR it
