### ISSUE TITLE
Uniformative runtime error(s)

### ISSUE THREAD

**Issue by kambysese** [ilogue/niprov#96]
I feel like we addressed these types of issue; and it seems like the error message(s) are rather unuseful, e.g., in this trace the file exists on the HD so what exactly is the problem?

> [provenance:info] Mnefun operation: apply_preprocessing_combined
> Traceback (most recent call last):
>   File "/home/ktavabi/Projects/ilabs/analysis_scripts/shiva.py", line 163, in <module>
>     print_status=True
>   File "/home/ktavabi/Projects/mnefun/mnefun/_mnefun.py", line 558, in do_processing
>     p.on_process(text, func, outs[ii], p)
>   File "/home/ktavabi/Projects/niprov/niprov/mnefunsupport.py", line 68, in handler
>     provenance.log(pcafile, trans, sssfile, provenance=customprov)
>   File "/home/ktavabi/Projects/niprov/niprov/context.py", line 26, in log
>     return niprov.logging.log(*args, dependencies=self.deps, **kwargs)
>   File "/home/ktavabi/Projects/niprov/niprov/logging.py", line 90, in log
>     listener.unknownFile(parents[0])
>   File "/home/ktavabi/Projects/niprov/niprov/commandline.py", line 45, in unknownFile
>     self.log(level, 'Unknown file: '+fpath, UnknownFileError)
>   File "/home/ktavabi/Projects/niprov/niprov/commandline.py", line 76, in log
>     raise exceptionClass(message)
> niprov.exceptions.UnknownFileError: Unknown file: /mnt/ALAYA/data/ilabs/shiva/meg/shiva_1081/sss_fif/shiva_1081_a_raw_sss.fif

**Comment by ilogue** [comment]
It means the parent file has not been added/discovered to provenance yet

**Comment by ilogue** [comment]
The ass file in this case

**Comment by kambysese** [comment]
Excuse me, the what file? Are you not taking me seriously? 😂😂😂😂

**Comment by ilogue** [comment]
Haha oops

**Comment by ilogue** [comment]
We could make the error about an unknown parent optional. Or check in the handler if the parent is known, and otherwise not specify a parent.

**Comment by kambysese** [comment]
We could throw a warning the parent file is missing and search for it before stopping the process?

**Comment by ilogue** [comment]
Search for it automatically? Or prompt the user to search for it?

Is it common in menfun to skip the early pipeline steps?

**Comment by kambysese** [comment]
And I could actually do that if I could actually understand what it is your doing in the code. Everything is constantly referring to something else!

**Comment by kambysese** [comment]
I'd say so, the processes are linear.
