### ISSUE TITLE
Some files end up without ID in database. 

### ISSUE THREAD

**Issue by ilogue** [ilogue/niprov#98]
```
ERROR:waitress:Exception when serving /id/None/pipeline
Traceback (most recent call last):
  File "/home/jasperb/Projects/pylabs/waitress-0.8.10-py2.7.egg/waitress/channel.py", line 336, in service
    task.service()
  File "/home/jasperb/Projects/pylabs/waitress-0.8.10-py2.7.egg/waitress/task.py", line 169, in service
    self.execute()
  File "/home/jasperb/Projects/pylabs/waitress-0.8.10-py2.7.egg/waitress/task.py", line 388, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/jasperb/Projects/pylabs/env/local/lib/python2.7/site-packages/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/jasperb/Projects/pylabs/env/local/lib/python2.7/site-packages/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/home/jasperb/Projects/pylabs/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/jasperb/Projects/pylabs/env/local/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/jasperb/Projects/pylabs/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/home/jasperb/Projects/pylabs/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 501, in _requestonly_view
    response = view(request)
  File "/home/jasperb/Projects/niprov/niprov/views.py", line 43, in pipeline
    return {'pipeline':pipeline.forFile(files.byId(sid)), 'sid':sid}
  File "/home/jasperb/Projects/niprov/niprov/mongo.py", line 145, in byId
    return self.factory.fromProvenance(record)
  File "/home/jasperb/Projects/niprov/niprov/files.py", line 60, in fromProvenance
    return self.locatedAt(provenance['location'], provenance)
TypeError: 'NoneType' object has no attribute '__getitem__'

```

i.e. http://0.0.0.0:6543/location/nara/mnt/ALAYA/data/ilabs/shiva/meg/shiva_4082/sss_pca_fif/shiva_4082_a_allclean_fil40_raw_sss.fif

**Comment by ilogue** [comment]
Maybe they failed to `inspect`or were `add`ed

**Comment by ilogue** [comment]
Might happen here:

https://github.com/ilogue/niprov/blob/master/niprov/files.py#L55

FileFactory detects that library is missing and therefore uses the Basefile constructor but forgets to pass provenance.
